### ISSUE TITLE
issue with deployment and a doubt on webhook configuration

### ISSUE THREAD

**Issue by nostorian** [Nirlep5252/EpicBot#77]
facing this issue when deploying: 
```diff
- ERROR: failed to launch: determine start command: when there is no default process a command is required
- ERROR: failed to launch: determine start command: when there is no default process a command is required
- ERROR: failed to launch: determine start command: when there is no default process a command is required
- ERROR: failed to launch: determine start command: when there is no default process a command is required
```
also for the webhook in config.py, do we have to enter the channel id or webhook id in the place of some random numbers there?

**Comment by Nirlep5252** [comment]
What host are you using? It's not an error in the bot, please ask for support from the host 
Also you need to enter webhook id

**Comment by nostorian** [comment]
i tried it again with a different host, but then this error popped up: 
```
Traceback (most recent call last):
File "/workspace/main.py", line 26, in <module>
client = EpicBot()
File "/workspace/utils/bot.py", line 99, in __init__
self.loop.run_until_complete(self.get_cache())
File "/app/.heroku/python/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
return future.result()
File "/workspace/utils/bot.py", line 361, in get_cache
self.prefixes_cache = await cursor.to_list(length=None)
File "/app/.heroku/python/lib/python3.9/site-packages/motor/core.py", line 1417, in _to_list
result = get_more_result.result()
File "/app/.heroku/python/lib/python3.9/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/app/.heroku/python/lib/python3.9/site-packages/pymongo/cursor.py", line 1130, in _refresh
self.__session = self.__collection.database.client._ensure_session()
File "/app/.heroku/python/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1935, in _ensure_session
return self.__start_session(True, causal_consistency=False)
File "/app/.heroku/python/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1883, in __start_session
server_session = self._get_server_session()
File "/app/.heroku/python/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1921, in _get_server_session
return self._topology.get_server_session()
File "/app/.heroku/python/lib/python3.9/site-packages/pymongo/topology.py", line 520, in get_server_session
session_timeout = self._check_session_support()
File "/app/.heroku/python/lib/python3.9/site-packages/pymongo/topology.py", line 499, in _check_session_support
self._select_servers_loop(
File "/app/.heroku/python/lib/python3.9/site-packages/pymongo/topology.py", line 218, in _select_servers_loop
raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 621513ea55539ff055ec1f1f, topology_type: Single, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused')>]>
ERROR:asyncio:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f46a948c520>
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending name='Task-1' coro=<Loop._loop() running at /app/.heroku/python/lib/python3.9/site-packages/discord/ext/tasks/__init__.py:153> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f46a950bd00>()]>>
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending name='Task-2' coro=<Loop._loop() running at /app/.heroku/python/lib/python3.9/site-packages/discord/ext/tasks/__init__.py:153> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f46a950be20>()]>>
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending name='Task-3' coro=<Loop._loop() running at /app/.heroku/python/lib/python3.9/site-packages/discord/ext/tasks/__init__.py:153> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f46a950ba60>()]>>
```

**Comment by Nirlep5252** [comment]
You haven't provided a correct mongoDB link

**Comment by GameWax** [comment]
now it shows this? wtf
task: <Task pending name='Task-1' coro=<Loop._loop() running at /app/.heroku/python/lib/python3.9/site-packages/discord/ext/tasks/__init__.py:153> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fed73222ee0>()]>>
ERROR:asyncio:Task was destroyed but it is pending!

**Comment by nostorian** [comment]
i have put correct mongo link at the MONGO value, i left the beta one blank, and the mongodb seems to be functioning well

**Comment by Nirlep5252** [comment]
Have you whitelisted the IP or are there any misconfigurations in your mongoDB cluster? 

Because it isn't able connect to the database. Read this: 
```
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused
```
